/**
 * All supported chains — mainnets + testnets
 * Mirrors viem/chains on the backend for validation & metadata
 */

const CHAINS = [
  // ── Mainnets ──────────────────────────────
  {
    id: 1,
    name: 'Ethereum',
    network: 'homestead',
    symbol: 'ETH',
    type: 'mainnet',
    explorer: 'https://etherscan.io',
    rpcUrl: `https://eth-mainnet.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    logoColor: '#627EEA',
    isTestnet: false,
  },
  {
    id: 137,
    name: 'Polygon',
    network: 'matic',
    symbol: 'MATIC',
    type: 'mainnet',
    explorer: 'https://polygonscan.com',
    rpcUrl: 'https://polygon-rpc.com',
    logoColor: '#8247E5',
    isTestnet: false,
  },
  {
    id: 42161,
    name: 'Arbitrum One',
    network: 'arbitrum',
    symbol: 'ETH',
    type: 'mainnet',
    explorer: 'https://arbiscan.io',
    rpcUrl: 'https://arb1.arbitrum.io/rpc',
    logoColor: '#28A0F0',
    isTestnet: false,
  },
  {
    id: 10,
    name: 'Optimism',
    network: 'optimism',
    symbol: 'ETH',
    type: 'mainnet',
    explorer: 'https://optimistic.etherscan.io',
    rpcUrl: 'https://mainnet.optimism.io',
    logoColor: '#FF0420',
    isTestnet: false,
  },
  {
    id: 8453,
    name: 'Base',
    network: 'base',
    symbol: 'ETH',
    type: 'mainnet',
    explorer: 'https://basescan.org',
    rpcUrl: 'https://mainnet.base.org',
    logoColor: '#0052FF',
    isTestnet: false,
  },
  {
    id: 43114,
    name: 'Avalanche',
    network: 'avalanche',
    symbol: 'AVAX',
    type: 'mainnet',
    explorer: 'https://snowtrace.io',
    rpcUrl: 'https://api.avax.network/ext/bc/C/rpc',
    logoColor: '#E84142',
    isTestnet: false,
  },
  {
    id: 56,
    name: 'BNB Chain',
    network: 'bsc',
    symbol: 'BNB',
    type: 'mainnet',
    explorer: 'https://bscscan.com',
    rpcUrl: 'https://bsc-dataseed.binance.org',
    logoColor: '#F0B90B',
    isTestnet: false,
  },
  {
    id: 250,
    name: 'Fantom',
    network: 'fantom',
    symbol: 'FTM',
    type: 'mainnet',
    explorer: 'https://ftmscan.com',
    rpcUrl: 'https://rpc.ftm.tools',
    logoColor: '#1969FF',
    isTestnet: false,
  },
  {
    id: 100,
    name: 'Gnosis',
    network: 'gnosis',
    symbol: 'xDAI',
    type: 'mainnet',
    explorer: 'https://gnosisscan.io',
    rpcUrl: 'https://rpc.gnosischain.com',
    logoColor: '#04795B',
    isTestnet: false,
  },
  {
    id: 1101,
    name: 'Polygon zkEVM',
    network: 'polygonZkEvm',
    symbol: 'ETH',
    type: 'mainnet',
    explorer: 'https://zkevm.polygonscan.com',
    rpcUrl: 'https://zkevm-rpc.com',
    logoColor: '#8247E5',
    isTestnet: false,
  },
  {
    id: 324,
    name: 'zkSync Era',
    network: 'zkSync',
    symbol: 'ETH',
    type: 'mainnet',
    explorer: 'https://explorer.zksync.io',
    rpcUrl: 'https://mainnet.era.zksync.io',
    logoColor: '#8C8DFC',
    isTestnet: false,
  },
  {
    id: 59144,
    name: 'Linea',
    network: 'linea',
    symbol: 'ETH',
    type: 'mainnet',
    explorer: 'https://lineascan.build',
    rpcUrl: 'https://rpc.linea.build',
    logoColor: '#61DFFF',
    isTestnet: false,
  },

  // ── Testnets ──────────────────────────────
  {
    id: 11155111,
    name: 'Sepolia',
    network: 'sepolia',
    symbol: 'ETH',
    type: 'testnet',
    explorer: 'https://sepolia.etherscan.io',
    rpcUrl: `https://eth-sepolia.g.alchemy.com/v2/${process.env.ALCHEMY_API_KEY}`,
    logoColor: '#627EEA',
    isTestnet: true,
  },
  {
    id: 17000,
    name: 'Holesky',
    network: 'holesky',
    symbol: 'ETH',
    type: 'testnet',
    explorer: 'https://holesky.etherscan.io',
    rpcUrl: 'https://ethereum-holesky.publicnode.com',
    logoColor: '#627EEA',
    isTestnet: true,
  },
  {
    id: 80002,
    name: 'Polygon Amoy',
    network: 'polygonAmoy',
    symbol: 'MATIC',
    type: 'testnet',
    explorer: 'https://amoy.polygonscan.com',
    rpcUrl: 'https://rpc-amoy.polygon.technology',
    logoColor: '#8247E5',
    isTestnet: true,
  },
  {
    id: 421614,
    name: 'Arbitrum Sepolia',
    network: 'arbitrumSepolia',
    symbol: 'ETH',
    type: 'testnet',
    explorer: 'https://sepolia.arbiscan.io',
    rpcUrl: 'https://sepolia-rollup.arbitrum.io/rpc',
    logoColor: '#28A0F0',
    isTestnet: true,
  },
  {
    id: 11155420,
    name: 'Optimism Sepolia',
    network: 'optimismSepolia',
    symbol: 'ETH',
    type: 'testnet',
    explorer: 'https://sepolia-optimism.etherscan.io',
    rpcUrl: 'https://sepolia.optimism.io',
    logoColor: '#FF0420',
    isTestnet: true,
  },
  {
    id: 84532,
    name: 'Base Sepolia',
    network: 'baseSepolia',
    symbol: 'ETH',
    type: 'testnet',
    explorer: 'https://sepolia.basescan.org',
    rpcUrl: 'https://sepolia.base.org',
    logoColor: '#0052FF',
    isTestnet: true,
  },
  {
    id: 43113,
    name: 'Avalanche Fuji',
    network: 'avalancheFuji',
    symbol: 'AVAX',
    type: 'testnet',
    explorer: 'https://testnet.snowtrace.io',
    rpcUrl: 'https://api.avax-test.network/ext/bc/C/rpc',
    logoColor: '#E84142',
    isTestnet: true,
  },
  {
    id: 97,
    name: 'BNB Testnet',
    network: 'bscTestnet',
    symbol: 'tBNB',
    type: 'testnet',
    explorer: 'https://testnet.bscscan.com',
    rpcUrl: 'https://data-seed-prebsc-1-s1.binance.org:8545',
    logoColor: '#F0B90B',
    isTestnet: true,
  },
  {
    id: 300,
    name: 'zkSync Sepolia',
    network: 'zkSyncSepoliaTestnet',
    symbol: 'ETH',
    type: 'testnet',
    explorer: 'https://sepolia.explorer.zksync.io',
    rpcUrl: 'https://sepolia.era.zksync.dev',
    logoColor: '#8C8DFC',
    isTestnet: true,
  },
  {
    id: 59141,
    name: 'Linea Sepolia',
    network: 'lineaSepolia',
    symbol: 'ETH',
    type: 'testnet',
    explorer: 'https://sepolia.lineascan.build',
    rpcUrl: 'https://rpc.sepolia.linea.build',
    logoColor: '#61DFFF',
    isTestnet: true,
  },
];

const getChainById   = (id)      => CHAINS.find(c => c.id === parseInt(id));
const getMainnets    = ()        => CHAINS.filter(c => !c.isTestnet);
const getTestnets    = ()        => CHAINS.filter(c =>  c.isTestnet);
const isValidChainId = (id)      => CHAINS.some(c => c.id === parseInt(id));

module.exports = { CHAINS, getChainById, getMainnets, getTestnets, isValidChainId };
